language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '9'
before_script:
  - npm prune
script:
  - npm run prepush
after_failure:
  - git status
  - git diff
after_success:
  # get the coverage metrics to coveralls
  - npm run coveralls-report
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
